In [1]:
import pickle
import numpy as np

In [5]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier

ohe_sex = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
ohe_embarked = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
clf = RandomForestClassifier()

In [6]:
import os
import pickle

os.makedirs('models', exist_ok=True)

pickle.dump(ohe_sex, open('models/ohe_sex.pkl', 'wb'))
pickle.dump(ohe_embarked, open('models/ohe_embarked.pkl', 'wb'))
pickle.dump(clf, open('models/clf.pkl', 'wb'))


In [7]:
# Assume user input
test_input = np.array([2, 'male', 31.0,0,0,10.5,'5'], dtype=object).reshape(1,7)

In [8]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, '5']], dtype=object)

In [19]:
test_input_sex = ohe_sex.fit_transform(test_input[:,1].reshape(1,1))

In [20]:
test_input_sex

array([[1.]])

In [22]:
test_input_embarked = ohe_embarked.fit_transform(test_input[:,-1].reshape(1,1))

In [23]:
test_input_embarked

array([[1.]])

In [24]:
test_input_age = test_input[:,2].reshape(1,1)

In [25]:
test_input_age

array([[31.0]], dtype=object)

In [26]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [27]:
test_input_transformed.shape

(1, 7)

In [29]:
from sklearn.ensemble import RandomForestClassifier
import pickle
import os

# Example: assuming X_train and y_train exist
clf = RandomForestClassifier()
clf.fit(X_train, y_train)  # Train the model

# Save the trained model
os.makedirs('models', exist_ok=True)
pickle.dump(clf, open('models/clf.pkl', 'wb'))


NameError: name 'X_train' is not defined