In [13]:
import numpy as np

# -------------------------
# Your Class (no changes)
# -------------------------
class MeraLR:
    
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
        
    def fit(self, X_train, y_train):
        X_train = np.insert(X_train, 0, 1, axis=1)
        betas = np.linalg.inv(X_train.T @ X_train) @ X_train.T @ y_train
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]
    
    def predict(self, X_test):
        y_pred = X_test @ self.coef_ + self.intercept_
        return y_pred

# -------------------------
# Step 1: Create sample data
# -------------------------
X = np.array([[1], [2], [3], [4], [5]])   # features
y = np.array([3, 5, 7, 9, 11])            # target

# -------------------------
# Step 2: Train-test split
# -------------------------
X_train = X[:4]
y_train = y[:4]

X_test = X[4:]
y_test = y[4:]

# -------------------------
# Step 3: Create object and train
# -------------------------
lr = MeraLR()
lr.fit(X_train, y_train)

# -------------------------
# Step 4: Predict
# -------------------------
y_pred = lr.predict(X_test)

print("Prediction:", y_pred)
print("Actual:", y_test)
print("Coefficient:", lr.coef_)
print("Intercept:", lr.intercept_)


Prediction: [11.]
Actual: [11]
Coefficient: [2.]
Intercept: 1.0


In [14]:
lr = MeraLR()

In [15]:
lr.fit(X_train,y_train)

In [17]:
X_train

array([[1],
       [2],
       [3],
       [4]])

In [18]:
lr.predict(X_test)

array([11.])

In [19]:
lr.coef_

array([2.])

In [20]:
lr.intercept_

np.float64(1.0)