In [2]:
from sklearn.datasets import load_diabetes

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [3]:
X,y = load_diabetes(return_X_y=True)

In [4]:
print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [5]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [6]:
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [7]:
print(reg.coef_)
print(reg.intercept_)

[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
151.88331005254167


In [8]:
y_pred = reg.predict(X_test)
r2_score(y_test,y_pred)

0.4399338661568968

In [9]:
import random

class MBGDRegressor:
    
    def __init__(self,batch_size,learning_rate=0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
        
    def fit(self,X_train,y_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            
            for j in range(int(X_train.shape[0]/self.batch_size)):
                
                idx = random.sample(range(X_train.shape[0]),self.batch_size)
                
                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
                #print("Shape of y_hat",y_hat.shape)
                intercept_der = -2 * np.mean(y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)

                coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [10]:
mbr = MBGDRegressor(batch_size=int(X_train.shape[0]/50),learning_rate=0.01,epochs=100)

In [11]:
mbr.fit(X_train,y_train)

151.73196495527316 [  29.13461613 -144.1461082   456.7083272   304.12333897  -25.28057558
  -96.70672986 -190.73410304  111.62446627  410.04110881  119.24861632]


In [12]:
y_pred = mbr.predict(X_test)

In [13]:
y_pred

array([152.48038901, 195.78291697, 130.9311664 , 105.42993979,
       260.20961718, 249.0269201 , 111.24122452, 115.27420943,
        94.79023475, 186.77081459, 149.25131305, 172.39250217,
       180.62360248, 140.02830696, 281.84080949,  87.38294194,
       196.76147998, 146.3351197 , 134.36604329, 132.07274731,
       144.27501731, 176.29248523, 154.04698229, 174.81298709,
       127.16558735, 222.45553285, 199.63064887, 105.91762837,
        55.43856435, 238.4362883 , 241.92033899, 113.90172354,
        68.33661814,  98.60732667, 203.45130126, 164.17368312,
       162.7352352 , 192.81378749, 113.09276562, 238.07958517,
       140.05663921, 121.94746447, 186.04650868, 186.02906534,
       173.91123808, 143.13107215, 170.6008545 , 294.22356641,
       108.32006688, 174.12520026, 250.7614407 , 138.85504212,
       149.22354309, 131.09558883, 191.02438269,  99.35517656,
       135.5943767 ,  78.52869002, 158.41404587, 152.08443253,
       162.70487815, 163.27579379, 104.05193745, 220.95

In [14]:
r2_score(y_test,y_pred)

0.4538085904940663

In [15]:
from sklearn.linear_model import SGDRegressor

In [16]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.1)

In [17]:
batch_size = 35

for i in range(100):
    
    idx = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx],y_train[idx])

In [18]:
sgd.coef_

array([  41.27146429,  -70.27884936,  329.17445009,  254.60935941,
         35.58604679,  -14.09814874, -158.6863147 ,  129.79877796,
        308.64936635,  103.99083147])

In [19]:
sgd.intercept_

array([174.5757858])

In [20]:
y_pred = sgd.predict(X_test)

In [21]:
r2_score(y_test,y_pred)

0.33958510609813064